name: Docker CI/CD for Django

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug Private Key Length
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -c

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # ✅ Make sure this matches the secret name
          script: |
            cd /home/CI-CD_project
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d --force-recreate
